import { test, expect, OWNER, apiGet, apiPost } from './fixtures';
import { maintenanceFixtures, tables } from './pr11-fixtures';
import type { FloorView, PoolTable, Session, StaffUser, SetupItem } from '../src/api/types';

for (const width of [1280, 400]) for (const theme of ['light', 'dark']) {
  test(`menus and rate help support pointer, focus and dismissal · ${width} · ${theme}`, async ({ page, signIn }) => {
    await page.setViewportSize({ width, height: 900 });
    await page.addInitScript(t => localStorage.setItem('supreme.theme.admin', t), theme);
    await maintenanceFixtures(page);
    await signIn(OWNER);
    await page.goto('/admin/tables');
    await expect(page.getByRole('button', { name: 'Change rate', exact: true })).toHaveCount(0);
    const help = page.getByRole('button', { name: 'Rate details for Table 1', exact: true });
    const tooltip = page.getByRole('tooltip');
    await help.hover();
    await expect(tooltip).toContainText('₱3.3333');
    await expect(tooltip).toContainText('₱199.998');
    await tooltip.hover();
    await expect(tooltip).toBeVisible();
    await page.getByRole('heading', { name: 'Pool tables', exact: true }).hover();
    await expect(tooltip).not.toBeVisible();
    await help.focus();
    await expect(tooltip).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(tooltip).not.toBeVisible();
    await expect(help).toBeFocused();
    await help.click();
    await expect(tooltip).toBeVisible();
    await help.click();
    await expect(tooltip).not.toBeVisible();
    await help.click();
    await page.getByRole('heading', { name: 'Pool tables', exact: true }).click();
    await expect(tooltip).not.toBeVisible();
    const trigger = page.getByRole('button', { name: 'Actions for Table 1', exact: true });
    await trigger.focus();
    await trigger.press('ArrowDown');
    await expect(page.getByRole('menuitem', { name: 'Edit', exact: true })).toBeFocused();
    await page.keyboard.press('ArrowDown');
    await expect(page.getByRole('menuitem', { name: 'Archive', exact: true })).toBeFocused();
    await page.keyboard.press('Escape');
    await expect(trigger).toBeFocused();
    await trigger.click();
    await page.getByRole('menuitem', { name: 'Edit', exact: true }).click();
    await expect(page.getByRole('dialog')).toHaveAccessibleName('Edit Table 1');
    await expect(page.getByLabel('Rate per hour', { exact: true })).toHaveValue('200');
    await page.getByRole('button', { name: 'Cancel', exact: true }).click();
    await page.goto('/admin/staff');
    await expect(page.getByText(/HELP\.md/)).toHaveCount(0);
    const owner = page.getByRole('row').filter({ hasText: 'Owner' });
    await expect(owner.getByRole('button', { name: 'Reset password', exact: true })).toBeDisabled();
    await owner.getByRole('button', { name: 'Actions for Owner', exact: true }).click();
    const archive = page.getByRole('menuitem', { name: /^Archive/ });
    await expect(archive).toHaveAttribute('aria-disabled', 'true');
    await expect(archive).toContainText('You cannot archive yourself.');
    await archive.focus();
    await archive.press('Enter');
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.keyboard.press('Escape');
    await page.getByRole('button', { name: 'Actions for Front Counter', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Edit', exact: true }).click();
    await expect(page.getByRole('dialog')).toHaveAccessibleName('Edit Front Counter');
    await page.getByRole('button', { name: 'Cancel', exact: true }).click();
    await page.getByRole('row').filter({ hasText: 'Front Counter' }).getByRole('button', { name: 'Reset password', exact: true }).click();
    await expect(page.getByRole('dialog')).toHaveAccessibleName("Reset Front Counter's password");
    await expect(page.locator('body')).toHaveJSProperty('scrollWidth', width);
  });
}

test('Edit saves both rate modes and existing sessions retain their snapshotted rates', async ({ page, signIn }) => {
  await signIn(OWNER);
  const table = await apiPost<PoolTable>(page.request, '/api/v1/tables', { name: 'PR11 hourly', ratePerHour: 200 });
  const customers = await apiGet<Array<{ id: string }>>(page.request, '/api/v1/customer-types');
  const session = await apiPost<Session>(page.request, '/api/v1/sessions', { tableId: table.id, customerTypeId: customers[0]!.id });
  await page.goto('/admin/tables');
  await page.getByRole('button', { name: 'Actions for PR11 hourly', exact: true }).click();
  await expect(page.getByRole('menuitem', { name: /^Archive/ })).toHaveAttribute('aria-disabled', 'true');
  await expect(page.getByRole('menuitem', { name: /^Archive/ })).toContainText('Close the open session');
  await page.getByRole('menuitem', { name: 'Edit', exact: true }).click();
  await expect(page.getByLabel('Rate per hour', { exact: true })).toHaveValue('200');
  await page.getByLabel('Name', { exact: true }).fill('PR11 renamed');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  for (const mode of ['minute', 'hour']) {
    await page.reload();
    await page.getByRole('button', { name: 'Actions for PR11 renamed', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Edit', exact: true }).click();
    await expect(page.getByLabel(mode === 'minute' ? 'Rate per hour' : 'Rate per minute', { exact: true })).toHaveValue(mode === 'minute' ? '200' : '2.1234');
    await page.getByRole('button', { name: mode === 'minute' ? 'Per minute' : 'Per hour', exact: true }).click();
    const input = page.getByLabel(mode === 'minute' ? 'Rate per minute' : 'Rate per hour', { exact: true });
    await expect(input).toHaveValue('');
    await input.fill(mode === 'minute' ? '2.1234' : '250');
    await page.getByRole('button', { name: 'Save', exact: true }).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    const read = (await apiGet<FloorView>(page.request, '/api/v1/tables')).tables.find(t => t.id === table.id)!;
    expect([read.ratePerHour, read.ratePerMinute, read.effectiveRatePerHour]).toEqual(mode === 'minute' ? [null, 2.1234, 127.404] : [250, 4.1667, 250.002]);
    const old = await apiGet<Session>(page.request, `/api/v1/sessions/${session.id}`);
    expect(old.segments[0]!.ratePerMinute).toBe(3.3333);
  }
  await page.reload();
  await page.getByRole('button', { name: 'Rate details for PR11 renamed', exact: true }).click();
  await expect(page.getByRole('tooltip')).toContainText('₱4.1667');
  await expect(page.getByRole('tooltip')).toContainText('₱250.002');
  await expect(page.getByRole('tooltip')).not.toContainText('under');
  await apiPost(page.request, `/api/v1/sessions/${session.id}/close`, {});
  await page.reload();
  await page.getByRole('button', { name: 'Actions for PR11 renamed', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Archive', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Archive', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByLabel('Show archived').check();
  const row = page.getByRole('listitem').filter({ hasText: 'PR11 renamed' });
  await row.getByRole('button', { name: 'Restore', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Actions for PR11 renamed', exact: true })).toBeVisible();
});

test('staff edit, password reset, archive/restore and unused deletion retain their server behavior', async ({ page, signIn }) => {
  await signIn(OWNER);
  const user = await apiPost<StaffUser>(page.request, '/api/v1/users', { username: 'pr11-counter', fullName: 'PR11 Counter', role: 'EMPLOYEE', temporaryPassword: 'temporary-pr11' });
  await page.goto('/admin/staff');
  await page.getByRole('button', { name: 'Actions for PR11 Counter', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Edit', exact: true }).click();
  await page.getByLabel('Full name', { exact: true }).fill('PR11 Evening Counter');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const row = page.getByRole('row').filter({ hasText: 'PR11 Evening Counter' });
  await row.getByRole('button', { name: 'Reset password', exact: true }).click();
  await page.getByLabel('Temporary password', { exact: true }).fill('replacement-pr11');
  await page.getByLabel('Confirm password', { exact: true }).fill('replacement-pr11');
  await page.getByRole('dialog').getByRole('button', { name: 'Reset password', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const read = (await apiGet<StaffUser[]>(page.request, '/api/v1/users')).find(u => u.id === user.id)!;
  expect(read.fullName).toBe('PR11 Evening Counter');
  expect(read.mustChangePassword).toBe(true);
  // Staff with activity must archive; a login makes the reset account historical.
  const login = await page.context().request.post('/api/v1/auth/login', { data: { username: 'pr11-counter', password: 'replacement-pr11' } });
  expect(login.ok()).toBe(true);
  await signIn(OWNER);
  await page.goto('/admin/staff');
  await page.getByRole('button', { name: 'Actions for PR11 Evening Counter', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Archive', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Archive', exact: true }).click();
  await expect(row).toHaveCount(0);
  await page.getByLabel(/Show archived/).check();
  await page.getByRole('listitem').filter({ hasText: 'PR11 Evening Counter' }).getByRole('button', { name: 'Restore', exact: true }).click();
  await expect(row).toContainText('inactive');
  const unused = await apiPost<StaffUser>(page.request, '/api/v1/users', { username: 'pr11-unused', fullName: 'PR11 unused', role: 'EMPLOYEE', temporaryPassword: 'temporary-pr11' });
  await page.reload();
  await page.getByRole('button', { name: 'Actions for PR11 unused', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Delete', exact: true }).click();
  await expect(page.getByRole('dialog')).toContainText('cannot be undone');
  await page.getByRole('button', { name: 'Delete permanently', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  expect((await apiGet<SetupItem[]>(page.request, '/api/v1/setup/staff')).some(u => u.id === unused.id)).toBe(false);
});

test('rate help and overflow menus work on a touch screen', async ({ browser }) => {
  const context = await browser.newContext({ baseURL: `http://localhost:${process.env.E2E_WEB_PORT ?? '5174'}`, hasTouch: true, viewport: { width: 400, height: 800 } });
  const page = await context.newPage();
  await context.request.post('/api/v1/auth/login', { data: OWNER });
  await maintenanceFixtures(page);
  await page.goto('/admin/tables');
  const help = page.getByRole('button', { name: 'Rate details for Table 1', exact: true });
  await help.tap();
  await expect(page.getByRole('tooltip')).toContainText('₱3.3333');
  await help.tap();
  await expect(page.getByRole('tooltip')).not.toBeVisible();
  await help.tap();
  await page.getByRole('button', { name: 'Actions for Table 1', exact: true }).tap();
  await expect(page.getByRole('tooltip')).not.toBeVisible();
  await page.getByRole('menuitem', { name: 'Edit', exact: true }).tap();
  await expect(page.getByRole('dialog')).toHaveAccessibleName('Edit Table 1');
  await context.close();
});

test('loading, failed eligibility, list failures and empty staff remain usable', async ({ page, signIn }) => {
  await maintenanceFixtures(page);
  await signIn(OWNER);
  let release!: () => void;
  const delayed = new Promise<void>(resolve => { release = resolve; });
  await page.route('**/api/v1/tables', async route => {
    await delayed;
    await route.fulfill({ status: 500, json: { success: false, message: 'Tables temporarily unavailable.' } });
  });
  await page.goto('/admin/tables');
  await expect(page.getByRole('status').filter({ hasText: 'Loading tables…' })).toBeVisible();
  release();
  await expect(page.getByRole('alert')).toContainText('Tables temporarily unavailable.');
  await page.route('**/api/v1/setup/staff', route => route.fulfill({ status: 500, json: { success: false, message: 'Could not check staff eligibility.' } }));
  await page.goto('/admin/staff');
  await page.getByRole('button', { name: 'Actions for Front Counter', exact: true }).click();
  await expect(page.getByRole('menuitem', { name: 'Checking…', exact: true })).toHaveAttribute('aria-disabled', 'true');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('alert')).toContainText('Could not check staff eligibility.');
  await expect(page.getByRole('button', { name: 'Retry', exact: true })).toBeEnabled();
  await page.route('**/api/v1/users', route => route.fulfill({ json: { success: true, data: [] } }));
  await page.reload();
  await expect(page.getByText('Nobody can sign in yet.', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'New staff', exact: true })).toBeEnabled();
});


test('dense tables keep help and menus inside a short phone viewport', async ({ page, signIn }) => {
  await page.setViewportSize({ width: 400, height: 480 });
  await maintenanceFixtures(page);
  const dense = Array.from({ length: 60 }, (_, i) => ({ ...tables[1]!, id: `table-${i}`, name: `Practice table ${i + 1}` }));
  await page.route('**/api/v1/tables', route => route.fulfill({ json: { success: true, data: { tables: dense, serverNow: new Date().toISOString() } } }));
  await signIn(OWNER);
  await page.goto('/admin/tables');
  const help = page.getByRole('button', { name: 'Rate details for Practice table 60', exact: true });
  await help.scrollIntoViewIfNeeded();
  await help.click();
  const tooltip = page.getByRole('tooltip');
  await expect(tooltip).toContainText('₱2.1234');
  await expect(tooltip).toContainText('₱127.404');
  const bounds = await tooltip.boundingBox();
  expect(bounds).not.toBeNull();
  expect(bounds!.x).toBeGreaterThanOrEqual(0);
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(400);
  expect(bounds!.y).toBeGreaterThanOrEqual(0);
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(480);
  await page.getByRole('button', { name: 'Actions for Practice table 60', exact: true }).click();
  await expect(page.getByRole('menuitem', { name: 'Edit', exact: true })).toBeInViewport();
  await page.keyboard.press('Escape');
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 400);
});
